//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class sudungdv
    {
        public string MaSDDV { get; set; }
        public string MaDV { get; set; }
        public string MaThuePhong { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgaySD { get; set; }
    
        public virtual dichvu dichvu { get; set; }
        public virtual thuephong thuephong { get; set; }
    }
}
